package sample.entities;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class Categories extends BaseTable implements TableOperations{

    public Categories() throws SQLException, ClassNotFoundException {
        super("categories");
    }

    @Override
    public void createTable() throws SQLException, ClassNotFoundException {
        super.executeSqlStatement("CREATE TABLE IF NOT EXISTS categories(" +
                "    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "    name character varying(150) NOT NULL);", "Обновлена таблица " + tableName);
    }

    @Override
    public void insertBaseDate(String sql) throws SQLException, ClassNotFoundException {

    }

    public long findIdByName(String name) throws  SQLException, ClassNotFoundException{
        reopenConnection();
        PreparedStatement ps = connection.prepareStatement("SELECT * FROM categories WHERE \"name\" = ?;");
        ps.setString(1,name);
        ResultSet result = ps.executeQuery();
        long categoryId = 0;
        while(result.next()){
            categoryId = result.getLong("id");
        }
        return categoryId;
    }


    public String findNamebyId(long id) throws SQLException, ClassNotFoundException {
        reopenConnection();
        PreparedStatement ps = connection.prepareStatement("SELECT * FROM categories WHERE \"id\" = ? ORDER BY name ASC;");
        ps.setLong(1,id);
        ResultSet result = ps.executeQuery();
        String category = null;
        while(result.next()){
            category = result.getString("name");
        }
        return category;
    }

    public void addCategory(String name) throws SQLException, ClassNotFoundException {
        reopenConnection();
        PreparedStatement ps = connection.prepareStatement("INSERT INTO categories (name) VALUES (?);");
        ps.setString(1, name);
        ps.executeUpdate();
        connection.close();
        System.out.println("Категория добавлена!");
    }

}
