package sample.entities;

import java.sql.SQLException;

public class CpuList extends BaseTable implements TableOperations {

    public CpuList() throws SQLException, ClassNotFoundException {
        super("cpu_list");
    }

    @Override
    public void createTable() throws SQLException, ClassNotFoundException {
        super.executeSqlStatement("CREATE TABLE IF NOT EXISTS cpu_list(" +
                "    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "    name character varying(20) COLLATE pg_catalog.default NOT NULL," +
                "    manufacturer character varying(20) COLLATE pg_catalog.default NOT NULL," +
                "    year smallint NOT NULL," +
                "    frequency numeric(2,1) NOT NULL," +
                "    price numeric(10,2) NOT NULL);", "Обновлена таблица " + tableName);
    }
    @Override
    public void insertBaseDate(String sql) throws SQLException, ClassNotFoundException {

    }

//    @Override
//    public ResultSet selectProducts() throws SQLException, ClassNotFoundException {
//        return super.select_all_products(tableName);
//    }

}
