package sample.entities;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class CpuList extends BaseTable implements TableOperations {

    public CpuList() throws SQLException, ClassNotFoundException {
        super("cpu_list");
    }

    @Override
    public void createTable() throws SQLException, ClassNotFoundException {
        super.executeSqlStatement("CREATE TABLE IF NOT EXISTS cpu_list(" +
                "    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "    name character varying(20) COLLATE pg_catalog.default NOT NULL," +
                "    manufacturer character varying(20) COLLATE pg_catalog.default NOT NULL," +
                "    year smallint NOT NULL," +
                "    frequency numeric(2,1) NOT NULL," +
                "    price numeric(10,2) NOT NULL);", "Обновлена таблица " + tableName);
    }
    @Override
    public void insertBaseDate(String sql) throws SQLException, ClassNotFoundException {
    }

    public void addCpu(String name, String manufacturer, int year, double frequency, double price) throws SQLException, ClassNotFoundException {
        reopenConnection();
        PreparedStatement ps = connection.prepareStatement("INSERT INTO cpu_list (name, manufacturer, year, frequency, price) VALUES (?, ?, ?, ?, ?);");
        ps.setString(1, name);
        ps.setString(2, manufacturer);
        ps.setInt(3, year);
        ps.setDouble(4, frequency);
        ps.setDouble(5, price);
        ps.executeUpdate();
        connection.close();

        System.out.println("Процессор добавлена!");
    }

    public String findNamebyId(long id) throws SQLException, ClassNotFoundException {
        reopenConnection();
        PreparedStatement ps = connection.prepareStatement("SELECT * FROM cpu_list WHERE \"id\" = ?;");
        ps.setLong(1, id);
        ResultSet result = ps.executeQuery();
        String cpuName = null;
        while(result.next()){
            cpuName = result.getString("name");
        }
        return cpuName;
    }

    public String allSpecificial(long id) throws SQLException, ClassNotFoundException {
        reopenConnection();
        PreparedStatement ps = connection.prepareStatement("SELECT * FROM cpu_list WHERE \"id\" = ?;");
        ps.setLong(1, id);
        ResultSet result = ps.executeQuery();
        String cpuManufacturer = null;
        String cpuName = null;
        String cpuFrequency = null;

        while(result.next()){
            cpuManufacturer = result.getString("manufacturer");
            cpuName = result.getString("name");
            cpuFrequency = result.getString("frequency");

        }
        return cpuManufacturer + " " + cpuName + " " + cpuFrequency + " Ггц";
    }

//    @Override
//    public ResultSet selectProducts() throws SQLException, ClassNotFoundException {
//        return super.select_all_products(tableName);
//    }

}
