package sample.entities;

import java.sql.SQLException;

public class VideocardsList extends BaseTable implements TableOperations{

    public VideocardsList() throws SQLException, ClassNotFoundException {
        super("videocard_list");
    }

    @Override
    public void createTable() throws SQLException, ClassNotFoundException {
        super.executeSqlStatement("CREATE TABLE IF NOT EXISTS videocard_list(" +
                "    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "    manufacturer character varying(20) COLLATE pg_catalog.\"default\" NOT NULL," +
                "    year smallint NOT NULL," +
                "    model integer NOT NULL," +
                "    \"ram\" integer NOT NULL," +
                "    price numeric(10,2) NOT NULL);", "Создана таблица " + tableName);
    }

    @Override
    public void insertBaseDate(String sql) throws SQLException, ClassNotFoundException {

    }

//    @Override
//    public ResultSet selectProducts() throws SQLException, ClassNotFoundException {
//        return super.select_all_products(tableName);
//    }

}
